Update backup-cronjob.yaml
influxdata/helm-charts pull request #222
Opened 2020-10-19 13:36 UTC by maksagit

Fix for selecting Linux node:
          nodeSelector:
            beta.kubernetes.io/os: linux

2020-10-20 23:55 UTC, naseemkullah commented
Thanks @maksagit , please add a configurable nodeSelector that defaults to `{}` for the backup component.

That would mean we add `Values.backup.nodeSelector`  with default value of `{}` and do something like https://github.com/jaegertracing/helm-charts/blob/1ca613f6ffb0205c145ef577792bf6264b93ca6c/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L71-L74

2020-10-20 23:56 UTC, naseemkullah requested changes
Thanks @maksagit , please add a configurable nodeSelector that defaults to {} for the backup component.

That would mean we add Values.backup.nodeSelector with default value of {} and do something like https://github.com/jaegertracing/helm-charts/blob/1ca613f6ffb0205c145ef577792bf6264b93ca6c/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L71-L74

2020-10-21 17:55 UTC, maksagit commented
Hello.
I don't know much about this.
If it's not difficult for you, could you add this fix with configurable
nodeSelector ?

ср, 21 окт. 2020 г. в 02:56, Naseem <notifications@github.com>:

> *@naseemkullah* requested changes on this pull request.
>
> Thanks @maksagit <https://github.com/maksagit> , please add a
> configurable nodeSelector that defaults to {} for the backup component.
>
> That would mean we add Values.backup.nodeSelector with default value of {}
> and do something like
> https://github.com/jaegertracing/helm-charts/blob/1ca613f6ffb0205c145ef577792bf6264b93ca6c/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L71-L74
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/helm-charts/pull/222#pullrequestreview-513216212>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDNRX2N6MS737VHJIRLJHLSLYPTFANCNFSM4SWFB74Q>
> .
>

2021-02-26 11:55 UTC, rawkode commented
Closing due to inactivity. Please feel free to cleanup and reopen if you find some time.

2021-02-26 11:55 UTC, closed without merging