use pod anti-affinity to support HA deployment by default
influxdata/helm-charts pull request #225
Opened 2020-10-22 12:58 UTC by pdrastil

Enterprise deployments should run in HA setup. This PR adds sensible default configuration that try to deploy data and meta containers on different workers in K8s cluster if possible by default.

2020-10-22 15:07 UTC, rawkode requested changes
Rather than baking this into the `values.yaml`, can we add it directly to the `Deployment` object?

IF a value is provided in the `values.yaml`, we use that instead.

2020-10-22 16:12 UTC, pdrastil commented
The reason why it's placed into values instead of hardcoded in StatefulSet is because you should allow modification of this configuration. I can imagine that someone would like to change this to `requiredDuringSchedulingIgnoredDuringExecution` or add additional rules with weights where to schedule pods in their cluster. This anti-affinity is just a starting point that should be good enough for most of the deployments.

2020-10-22 16:57 UTC, rawkode approved these changes

2020-10-22 16:57 UTC, rawkode commented
It's not a big deal, I can tidy up the logic afterwards if needed.

Thanks

2020-10-23 11:49 UTC, sumo-drosiek approved these changes
LGTM

2020-10-23 17:43 UTC, merged