Make readiness and liveness checks configurable
influxdata/helm-charts pull request #270
Opened 2021-02-15 10:01 UTC by fredericOfTestfabrik

The choosen defaults for readiness/liveness checks may trigger unnecessary container restarts, because timeouts may be too low. 

I simply introduced a readiness/liveness config options and used the in the statefulset.yaml. 

I tested my changes by locally installing the chart and checking if the values were set correctly.

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-02-19 14:20 UTC, rawkode commented
Hi @fredericOfTestfabrik,

Thanks. This looks great. I'm OK with the timeouts being configurable, but don't believe we should make the port or path configurable.

Can you remove those options, please?

2021-02-19 14:34 UTC, fredericOfTestfabrik commented
I'm a fan of make everything available to the end user but I guess you are right, in this case it doesn't really make sense.

I removed the options as requested.

2021-02-26 12:11 UTC, rawkode submitted a review, later dismissed

2021-02-27 16:10 UTC, timhallinflux requested changes
Chart version needs a bump

2021-03-19 14:50 UTC, fredericOfTestfabrik commented
Sorry. Unfortunately I was very busy. I bumped the version as requested.

2021-12-10 13:16 UTC, Tonow commented
I think this PR is more complete https://github.com/influxdata/helm-charts/pull/381

2022-01-03 17:47 UTC, timhallinflux commented
closing in favor of #381

2022-01-03 17:47 UTC, closed without merging