[influxdb2] Add backup cronjob
influxdata/helm-charts pull request #321
Opened 2021-05-29 15:48 UTC by abhi1693

- Adds backup cronjob using [rclone](https://rclone.org/)
- Bumps chart to `2.0.2`

2021-05-29 15:53 UTC, abhi1693 commented
@rawkode @timhallinflux Kindly give this a try whenever you can :)

2021-06-04 21:33 UTC, timhallinflux approved these changes

2021-12-13 17:36 UTC, florianrusch commented
@rawkode @timhallinflux @abhi1693 can we bring some progress on this? I really looking forward to it and would like to help out if I can!

2021-12-13 18:04 UTC, abhi1693 commented
@florianrusch I also submitted a similar PR at https://github.com/bitnami/charts/pull/8317 if you are interested

2021-12-13 18:26 UTC, florianrusch requested changes

2021-12-13 18:26 UTC, florianrusch commented on charts/influxdb2/templates/_helpers.tpl
> +{{- end -}}
Why do you need it? You only use it in the cronjob. There is no SA resource anywhere or?

2022-09-05 04:11 UTC, abhi1693 commented
Closing since maintainers are unresponsive

2022-09-05 04:11 UTC, closed without merging