expose syslog port
influxdata/helm-charts pull request #401
Opened 2022-01-01 15:10 UTC by aSauerwein

automatically expose syslog port as defined in config.inputs
this fixes issue #164 
```
- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
```

2022-01-04 13:54 UTC, alespour requested changes

2022-01-04 13:54 UTC, alespour commented on charts/telegraf/templates/service.yaml
> +  - port: {{ regexFind "[0-9]+$" $value.server  | int64 }}
To make it safe I'd suggest to add protocol condition check (with unix socket server address the rendered port spec is invalid), eg.

```suggestion
    {{- if eq $key "syslog" }}
      {{- if regexMatch "^(tcp|udp).*" $value.server }}
  - port: {{ regexFind "[0-9]+$" $value.server  | int64 }}
```

2022-01-04 13:54 UTC, alespour commented on charts/telegraf/templates/service.yaml
> +    {{- end }}
```suggestion
      {{- end }}
    {{- end }}
```

2022-01-20 09:39 UTC, alespour commented
Closes #164

2022-01-20 10:14 UTC, alespour approved these changes

2022-01-20 15:09 UTC, tomklapka commented
Does it make sense to you @alespour to improve also other Telegraf charts (telegraf-ds, telegraf-operator) ?

2022-01-20 15:18 UTC, timhallinflux approved these changes

2022-01-20 17:10 UTC, alespour commented
> Does it make sense to you @alespour to improve also other Telegraf charts (telegraf-ds, telegraf-operator) ?

It is not applicable - `telegraf-ds` has hardcoded inputs without syslog and `telegraf-ds` has no input plugins

2022-01-20 17:10 UTC, merged