add image pull secret
influxdata/helm-charts pull request #482
Opened 2022-06-20 10:33 UTC by ChristophKuper

2022-06-30 08:35 UTC, alespour requested changes
Regarding the last commit, there is no InfluxDB 2.2.1 version unfortunately, could you please change it to the latest, 2.3.0?
Thank you for the contribution.

2022-07-11 09:29 UTC, alespour approved these changes
LGTM now

2022-07-21 11:50 UTC, tomklapka approved these changes

2022-10-10 13:52 UTC, ChristophKuper commented
would be nice if this could be merged

2022-10-10 15:22 UTC, merged